#!/usr/bin/env bash

# Install all scripts in `./bin` to `/usr/local/bin`.
# Run as sudo
ls ./bin |
while read filename
do
  chmod +x $PWD/bin/$filename
  ln -s $PWD/bin/$filename /usr/local/bin
done 
